### ISSUE TITLE
Mnemonic Passphrase?

### ISSUE THREAD

**Issue by DarkCross71** [greenaddress/WalletCordova#33] opened 2015-09-22 02:26 UTC
I'm sure this topic has been brought up, but I am hoping there may be a chance to retrieve my coins? I wrote the phrase down and even looked every word up in the list, every word is correct. I even put in words that were close in spelling, no luck.

Am I out of luck? Can someone hack into my account, I have 150.00, all I ask for is 100.00, you can keep the rest?

**Comment by greenaddress** [comment] 2015-09-22 07:55
Hello,

What is the issue you are experiencing with the mnemonic passphrase? 

Either way we can't keep any funds for ourselves (by design) and we do not intend to ask money for help.

**Comment by DarkCross71** [comment] 2015-09-22 14:53
Hello, 


When I enter my passpharse, it will not let me login too my account? I wrote it down word for word, I have it stored on three thumb drives and I even checked it against the list of words you guys have....every word is correct. I checked other words that are similar and still can't get into my account? 


I am at a loss, any help you can provide would be greatly appreciated. 


Thank you

**Comment by DarkCross71** [comment] 2015-09-25 14:16
Anyone? Any help would be appreciated, there has to be a way to get my money out...

**Comment by greenaddress** [comment] 2015-09-25 14:38
How many words is the mnemonic passphrase?

What error do you get when you try to login? 

Did you try within our Chrome App and/or GreenBits?

At this time GreenBits (for Android) is the one that does the best error checking (i.e. it tells you if there's a typo and in which word and which word looks closest from the list of valid words)

Thanks

**Comment by DarkCross71** [comment] 2015-09-25 14:45
Here is the phrase:
timber turtle foster awesome head until fix claw puzzle prevent juice alone always ozone clerk ice tongue ginger rough cook original gain matter split crouch laugh accuse
Every word is checked and spelled correct...
The error I get is :checksum does not match


 


     On Friday, September 25, 2015 7:38 AM, GreenAddress <notifications@github.com> wrote:
   

 How many words is the mnemonic passphrase?What error do you get when you try to login? Did you try within our Chrome App and/or GreenBits?At this time GreenBits (for Android) is the one that does the best error checking (i.e. it tells you if there's a typo and in which word and which word looks closest from the list of valid words)Thanks—

**Comment by DarkCross71** [comment] 2015-09-25 14:46
timber turtle foster awesome head until fix claw puzzle prevent juice alone always ozone clerk ice tongue ginger rough cook original gain matter split crouch laugh accuse

Every word is checked and spelled correct...

The error I get is :checksum does not match

**Comment by greenaddress** [comment] 2015-09-25 14:53
Do NOT post here mnemonics (do not send them to us in any way, not via GitHub, not via email, not even PGP encrypted - we do not want to have your mnemonic passphrase and we will never ask for it)

I hope nobody managed to copy it before I deleted it but it is possible someone got hold of it and if they did they can easily steal your money (unless you have setup 2FA but even so I'd avoid it)

**Comment by DarkCross71** [comment] 2015-09-25 14:56
Shit, I am sorry....thank you for deleting it!

**Comment by DarkCross71** [comment] 2015-09-25 14:57
So, is there anything that can be done?

**Comment by greenaddress** [comment] 2015-09-25 15:13
When was it last that you logged in with the mnemonics and it worked?

Did you take the words from a piece of paper written by hand?

Was there any word that you weren't sure about and you found one that looked similar inside the list ( https://raw.githubusercontent.com/greenaddress/GreenBits/56ac4844c8798e1dff45a6fd1332600154b6b7e1/app/src/main/assets/bip39-wordlist.txt) ? 

Do not provide the word on Github: if there were some that you are in doubt with see if there's another word that is similar inside the file and use that instead.

Also: Order is fundamental, if you disordered the words then indeed it wouldn't work and you'd have a checksum issue as per your problem.

**Comment by DarkCross71** [comment] 2015-09-25 15:26
I loggin in about three months ago, everything was good,I could see all my tabs, receive, send etc...
I tried everything you suggested, word that was close or maybe misspelled a little, I tried everything... 
 


     On Friday, September 25, 2015 8:13 AM, GreenAddress <notifications@github.com> wrote:
   

 When was it last that you logged in with the mnemonics and it worked?Did you take the words from a piece of paper written by hand?Was there any word that you weren't sure about and you found one that looked similar inside the list ( https://raw.githubusercontent.com/greenaddress/GreenBits/56ac4844c8798e1dff45a6fd1332600154b6b7e1/app/src/main/assets/bip39-wordlist.txt) ? Do not provide the word on Github: if there were some that you are in doubt with see if there's another word that is similar inside the file and use that instead.Also: Order is fundamental, if you disordered the words then indeed it wouldn't work and you'd have a checksum issue as per your problem.—

**Comment by greenaddress** [comment] 2015-09-25 15:46
From what you say and from the checksum error it appears that either:

a) The order of the words is wrong

b) One or more words are wrong

All I can suggest is that you look back at your hand written backup and see if some specific words was not too clear and maybe the one you selected from the list wasn't the actual match.

For example the dictionary file contains words like: ice, dice, device, juice and in some hand writings they may appear too similar.

Hope this helps!

**Comment by DarkCross71** [comment] 2015-09-26 21:22
I looked throughout the list, some words were similar and I tried to enter the similar words back and forth every which way, but nothing worked. 

It worked like I said a few months back...
  


     On Friday, September 25, 2015 8:13 AM, GreenAddress <notifications@github.com> wrote:
   

 When was it last that you logged in with the mnemonics and it worked?Did you take the words from a piece of paper written by hand?Was there any word that you weren't sure about and you found one that looked similar inside the list ( https://raw.githubusercontent.com/greenaddress/GreenBits/56ac4844c8798e1dff45a6fd1332600154b6b7e1/app/src/main/assets/bip39-wordlist.txt) ? Do not provide the word on Github: if there were some that you are in doubt with see if there's another word that is similar inside the file and use that instead.Also: Order is fundamental, if you disordered the words then indeed it wouldn't work and you'd have a checksum issue as per your problem.—

**Comment by DarkCross71** [comment] 2015-09-26 21:23
I looked throughout the list, some words were similar and I tried to enter the similar words back and forth every which way, but nothing worked.

It worked like I said a few months back...

**Comment by smilzoboboz** [comment] 2016-04-13 11:01
I just installed the latest android release (0.0.76) and I was only able to login through the read-only paraphrase login.

Either reading the mnemonic (unencrypted) from QR-code or writing it down word by word didn't work, all I get is a red message saying "Invalid mnemonic: {}"

My mnemonic counts 24 space-separated english words.

**Comment by greenaddress** [comment] 2016-04-13 11:05
@smilzoboboz are you the same person as @DarkCross71 or someone else?

try https://play.google.com/store/apps/details?id=com.greenaddress.greenbits_android_wallet&hl=en, it will auto detect any invalid word and even suggest correction for typos

Did you confirm each word is present in https://raw.githubusercontent.com/greenaddress/GreenBits/56ac4844c8798e1dff45a6fd1332600154b6b7e1/app/src/main/assets/bip39-wordlist.txt ?

**Comment by smilzoboboz** [comment] 2016-04-13 11:15
I'm another person, as for the GreenBits app, that is what I'm currently using on my phone, but since it's days it keeps crashing (I read that they should be fixed now) I wanted to try the other one.

Also, I just checked that every word on my mnemonic matches with words on that list.

**Comment by greenaddress** [comment] 2016-04-13 11:24
If every word matches it may be an order issue; GreenBits had some issues on some Android versions but should be fixed now, I'd suggest trying that to see if it helps (it's a different implementation) if it does have issues please let us know

**Comment by smilzoboboz** [comment] 2016-04-13 11:34
I'm quite sure (read totally sure) that the word order is correct. As I wrote before I read the QR-code of my mnemonic (from chromium extension) before trying word by word and I got the same error message.
This same mnemonic is also what I used on the chromium app almost a year ago and on the GreenBits app few months ago.

Ofc I will be using the GreenBits app on my phone (hoping it doesn't crash on me like it used to these past days) but I just wanted to point out that there something wrong with the mnemonic authentication on this app.

**Comment by greenaddress** [comment] 2017-04-26 16:21
I believe this should be fixed (i.e. the problem above should be caused by a space at the end of the mnemonics). If not, feel free to reopen.

**Closed by greenaddress** 2017-04-26 16:21 UTC

**Comment by harrypnyce** [comment] 2017-10-03 18:08
Having a similar issue attempting to restore my 12 word seed phrase, now receiving:   **Invalid mnemonic: Checksum does not match**

I've confirmed that there is no space at the end of the wallet (tried both with and without).  I'm attempting to restore from Electrum 2.7.9 Wallet that has been giving me problems recently.
